

name: CI-CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    # =========================
    # FIX: kubeconfig (IMPORTANT)
    # =========================
    - name: Setup kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
        kubectl config view
        kubectl cluster-info

      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    # =========================
    # VERIFY CONNECTION
    # =========================
    - name: Verify cluster
      run: |
        kubectl get nodes

    # =========================
    # DEPLOY DEV
    # =========================
    - name: Deploy DEV
      if: github.ref == 'refs/heads/dev'
      run: kubectl apply --validate=false -f k8s/dev/

    # =========================
    # DEPLOY TEST
    # =========================
    - name: Deploy TEST
      if: github.ref == 'refs/heads/test'
      run: kubectl apply --validate=false -f k8s/test/

    # =========================
    # DEPLOY PROD
    # =========================
    - name: Deploy PROD
      if: github.ref == 'refs/heads/prod'
      run: kubectl apply --validate=false -f k8s/prod/


















