

name: CI-CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # =========================
    # Setup kubectl
    # =========================
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    # =========================
    # Setup kubeconfig (IMPORTANT FIX)
    # =========================
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    # =========================
    # Verify cluster connection
    # =========================
    - name: Check cluster
      run: |
        kubectl config current-context
        kubectl get nodes

    # =========================
    # Deploy DEV
    # =========================
    - name: Deploy to DEV
      if: github.ref == 'refs/heads/dev'
      run: kubectl apply --validate=false -f k8s/dev/

    # =========================
    # Deploy TEST
    # =========================
    - name: Deploy to TEST
      if: github.ref == 'refs/heads/test'
      run: kubectl apply --validate=false -f k8s/test/

    # =========================
    # Deploy PROD (with approval style gate)
    # =========================
    - name: Deploy to PROD
      if: github.ref == 'refs/heads/prod'
      run: kubectl apply --validate=false -f k8s/prod/

































































