








name: Multi Environment Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy RBAC
        run: |
          kubectl apply -f k8s/dev/sa.yaml
          kubectl apply -f k8s/dev/role.yaml
          kubectl apply -f k8s/dev/rolebinding.yaml

      - name: Deploy App
        run: |
          kubectl apply -f k8s/dev/deployment.yaml
          kubectl apply -f k8s/dev/service.yaml








































































































